### ISSUE TITLE
CAS or concurrent modification issue, in case of multiple ajax calls on page load.

### ISSUE THREAD

**Issue by ShajahanEM** [mkopylec/session-couchbase-spring-boot-starter#7]
Hi,
   Getting the "CAS mismatch or concurrent modification Failed to perform update" , in case of multiple ajax calls on page load. In the angular js application, we have mutiple ajax calls happening on page load which is leading to concurrent modification issue. Able to fix it with save instead of two updates. Let know how to share the same. 

org.springframework.data.couchbase.core.CouchbaseQueryExecutionException: Error executing N1QL statement 'UPDATE ssui_empact_sit USE KEYS $1 SET data.`global` = $2'. [{"msg":"DML Error, possible causes include CAS mismatch or concurrent modificationFailed to perform update - cause: MCResponse status=KEY_EEXISTS, opcode=SET, opaque=0, msg: Data exists for key","code":12009}]
                at com.github.mkopylec.sessioncouchbase.persistent.CouchbaseDao.executeQuery(CouchbaseDao.java:99) ~[session-couchbase-spring-boot-starter-0.1.0-SNAPSHOT.jar:na]
                at com.github.mkopylec.sessioncouchbase.persistent.CouchbaseDao.updateSession(CouchbaseDao.java:36) ~[session-couchbase-spring-boot-starter-0.1.0-SNAPSHOT.jar:na]
                at com.github.mkopylec.sessioncouchbase.persistent.CouchbaseSessionRepository.save(CouchbaseSessionRepository.java:73) ~[session-couchbase-spring-boot-starter-0.1.0-SNAPSHOT.jar:na]
                at com.github.mkopylec.sessioncouchbase.persistent.CouchbaseSessionRepository.save(CouchbaseSessionRepository.java:19) ~[session-couchbase-spring-boot-starter-0.1.0-SNAPSHOT.jar:na]
                at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.commitSession(SessionRepositoryFilter.java:194) ~[spring-session-1.1.0.RELEASE.jar:na]
                at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.access$100(SessionRepositoryFilter.java:170) ~[spring-session-1.1.0.RELEASE.jar:na]
                at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:128) ~[spring-session-1.1.0.RELEASE.jar:na]
                at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:65) ~[spring-session-1.1.0.RELEASE.jar:na]

**Comment by mkopylec** [comment]
Using `save` method is not a proper solution for this bug.
When `save` is used it can lead to another bug which is overwriting another apps namespaces with old data because `save` replaces whole document content.
The structure of the session document is:

``` json
{
  "global": {...},
  "app_1_namespace": {...},
  "app_2_namespace": {...}
}
```

I think the only valid solution here is retrying the update operation.
Is this the solution you can accept?

**Comment by ShajahanEM** [comment]
Actually already tried with retries, which didn't help and not works all the times. Fetch, conditional replacement of application namespace value based on the session.isNamespacePersistenceRequired() and then save, worked for single namespace. Not clear about the  multiple application namespaces because the createSession method always creates sessionData map of size two ( Map<String, Map<String, Object>> sessionData = new HashMap<>(2);) .

**Comment by mkopylec** [comment]
Thanks for the comment, I will analyze the bug by providing some detailed unit tests and then I will try to find a valid solution, if any exists.

**Comment by mkopylec** [comment]
From 2.0.0 you can enable Couchbase [query retrying](https://github.com/mkopylec/session-couchbase-spring-boot-starter#retrying) which can prevent the CAS errors in your app.
[Here](https://github.com/mkopylec/session-couchbase-spring-boot-starter/blob/master/src/test/groovy/com/github/mkopylec/sessioncouchbase/specification/concurrency/PersistentConcurrentModificationsSpec.groovy) is the integration test for it
