### ISSUE TITLE
Couchbase 4.5.1 bug

### ISSUE THREAD

**Issue by jonnydahlberg** [mkopylec/session-couchbase-spring-boot-starter#9]
Hi,

There's been a behavior change in Couchbase 4.5.1. Path expression in the FROM clause is no longer supported which causes the lib to break.

Please see:
http://developer.couchbase.com/documentation/server/4.5/release-notes/relnotes.html#topic_gbk_tyh_t5__release-451

Thanks!
Jonny

### Stack trace:
016-12-14 14:49:12.801 ERROR 15324 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[/sl].[dispatcherServlet]  : Servlet.service() for servlet [dispatcherServlet] in context with path [/sl] threw exception

org.springframework.data.couchbase.core.CouchbaseQueryExecutionException: **Error executing N1QL statement 'SELECT * FROM default.data.`global` USE KEYS $1'. [{"msg":"syntax error - at .","code":3000}]**
    at com.github.mkopylec.sessioncouchbase.persistent.CouchbaseDao.executeQuery(CouchbaseDao.java:87) ~[session-couchbase-spring-boot-starter-1.2.2.jar:na]
    at com.github.mkopylec.sessioncouchbase.persistent.CouchbaseDao.findSessionAttributes(CouchbaseDao.java:43) ~[session-couchbase-spring-boot-starter-1.2.2.jar:na]
    at com.github.mkopylec.sessioncouchbase.persistent.CouchbaseSessionRepository.getSession(CouchbaseSessionRepository.java:88) ~[session-couchbase-spring-boot-starter-1.2.2.jar:na]
    at com.github.mkopylec.sessioncouchbase.persistent.CouchbaseSessionRepository.getSession(CouchbaseSessionRepository.java:19) ~[session-couchbase-spring-boot-starter-1.2.2.jar:na]
    at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.getSession(SessionRepositoryFilter.java:326) ~[spring-session-1.2.1.RELEASE.jar:na]
    at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.getSession(SessionRepositoryFilter.java:343) ~[spring-session-1.2.1.RELEASE.jar:na]
    at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.getSession(SessionRepositoryFilter.java:214) ~[spring-session-1.2.1.RELEASE.jar:na]
    at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:231) ~[tomcat-embed-core-8.5.4.jar:8.5.4]
    at org.springframework.security.web.context.HttpSessionSecurityContextRepository.loadContext(HttpSessionSecurityContextRepository.java:110) ~[spring-security-web-4.1.1.RELEASE.jar:4.1.1.RELEASE]
    at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:100) ~[spring-security-web-4.1.1.RELEASE.jar:4.1.1.RELEASE]
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331) ~[spring-security-web-4.1.1.RELEASE.jar:4.1.1.RELEASE]
    at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) ~[spring-security-web-4.1.1.RELEASE.jar:4.1.1.RELEASE]

**Comment by mkopylec** [comment]
Hi Jonny. Thanks for reporting the bug.

**Comment by mkopylec** [comment]
Fixed in 2.0.1
